/* Generated by RuntimeBrowser.
 */

@protocol UITextDragSupporting <UITextDraggable>

@required

- (bool)allowsDraggingAttachments;
- (bool)allowsEditingTextAttributes;
- (void)draggingFinished:(id <UITextDragFinishState>)arg1;
- (void)draggingStarted;

@optional

- (bool)_shouldObscureInput;
- (void)didGenerateCancelPreview:(id)arg1;
- (void)performCancelAnimations;
- (id)willGenerateCancelPreview;

@end
