/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLPostVertexDumpOutput : NSObject {
    NSString * _airMDType;
    unsigned long long  _dataType;
    NSString * _name;
    unsigned long long  _offset;
}

@property (readonly) NSString *airMDType;
@property (readonly) unsigned long long dataType;
@property (readonly) NSString *name;
@property (readonly) unsigned long long offset;

- (id)airMDType;
- (unsigned long long)dataType;
- (void)dealloc;
- (id)description;
- (id)formattedDescription:(unsigned long long)arg1;
- (id)initWithAirMDType:(id)arg1 dataType:(unsigned long long)arg2 name:(id)arg3 offset:(unsigned long long)arg4;
- (id)name;
- (unsigned long long)offset;

@end
