/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEODataSessionTaskRequesterOp : NSObject <GEOProtobufSessionTaskDelegate> {
    NSString * _appIdentifier;
    bool  _canceled;
    id /* block */  _completionHandler;
    GEODataRequest * _dataRequest;
    NSString * _debugRequestName;
    int  _experimentDispatcherRequestType;
    PBRequest * _request;
    unsigned char  _requestCounterInfoType;
    NSNumber * _serviceTypeNumber;
    GEOProtobufSessionTask * _task;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_cleanup;
- (id)_userInfoForTask:(id)arg1;
- (void)cancel;
- (void)dealloc;
- (id)initWithRequest:(id)arg1 auditToken:(id)arg2 urlType:(unsigned long long)arg3 additionalURLQueryItems:(id)arg4 additionalHTTPHeaders:(id)arg5 debugRequestName:(id)arg6 serviceType:(id)arg7 experimentType:(long long)arg8 experimentDispatcherRequestType:(int)arg9 requestCounterInfoType:(unsigned char)arg10 timeout:(double)arg11 shouldThrottleRequests:(bool)arg12 throttleKey:(id)arg13 dataRequestKind:(int)arg14 traits:(id)arg15;
- (void)protobufSession:(id)arg1 didCompleteTask:(id)arg2;
- (void)startWithCompletionHandler:(id /* block */)arg1;

@end
